name: CI

on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16, 18 ]
    steps:
      - uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: yarn install
        run: yarn install
      - name: tsc
        uses: icrawl/action-tsc@v1
      - name: yarn build
        run: yarn build
      - name: yarn test
        run: yarn test
      - name: codecov
        uses: codecov/codecov-action@v3
        with:
          # token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          name: codecove # optional
          flags: unittest
          verbose: true # optional (default = false)
